site_name: Carlos Cardenas
site_url: https://www.carlos-cardenasbravo.com/
theme:
    name: simple-blog
    colors:
      primary: black
markdown_extensions:
  - admonition

nav:
  - Home: index.md
  - About: about.md
  - Articles: 
    - Name: articles/art01.md
  - Publications:
    - WCPEC-8-01: papers/paper01.md
    - WCPEC-8-02: papers/paper02.md
